name: Daily Mood Score
on:
  schedule:
    - cron: '0 2 * * *'    # 02:00 UTC = 07:30 IST daily
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - run: python src/mood_score.py
      - name: Commit updated CSV
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: CI update daily_dashboard.csv'
          file_pattern: out/daily_dashboard.csv
